# Python

1.Write a program using list comprehension to find primes 
in range 2 to 100.

In [7]:
primes=[x for x in range(2,100) if all(x%y!=0 for y in range (2,x))]
print(primes)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


2.Write a function to reverse a string

string='reverse a string'

In [8]:
def string_rev(x):
    return x[::-1]

string=string_rev('reverse a string')


In [10]:
print(string)

gnirts a esrever


3.Write a program to extract the words from the given list which have their first character in uppercase. Days = ['Monday', 'tuesday','friday', 'Sunday', 'Saturday']

Output: ['Monday', 'Sunday', 'Saturday'

In [72]:
x= ['Monday', 'tuesday','friday', 'Sunday', 'Saturday']
for i in x:
    if i[0].isupper():
        print(i)


Monday
Sunday
Saturday


4.Write a program to extract the year part from the dates in 
the given list.

modBatch = ['15-06-1997','15-06-2011','15-06-1993','15-06-2020']

Output: ['1997','2011','1993','2020']

In [3]:
Batch = ['15-06-1997','15-06-2011','15-06-1993','15-06-2020']
Batch=[x.split("-")[2] for x in Batch]
print(Batch)

['1997', '2011', '1993', '2020']


5.Write a program swap the keys to values and values to keys of the given dictionary. 

Module = {'Data Science':1,'Machine Learning':2, 'SQL':3, 'Big Data':4} 

Output: {1:'Data Science',2:'Machine Learning', 3:'SQL', 4:'Big Data'}

In [34]:
Module = {'Data Science':1,'Machine Learning':2, 'SQL':3, 'Big Data':4}
swap={v:k for k,v in Module.items()}
print(swap)

{1: 'Data Science', 2: 'Machine Learning', 3: 'SQL', 4: 'Big Data'}


6.Write a program to count the number of elements in the string (given by the user) that are not present in the 'my_string'. 

Do not count the white spaces.

my_string = 'Data Science'

In [8]:
def count(s1,s2):
    c=""
    j=0
    for i in s1:
        if s2.find(i)<-0 and j==s1.find(i):
            c=c+i
        j=j+1
    x=c.replace("","")
    print(len(x))
    
user_string=input()
my_string="DataScience"
count(user_string,my_string)

Machinelearning
5


7.Define a function to check whether a number is in a range (1000,10000) or not.

In [5]:
def check_range(n):
    if n>1000 and n<10000:
        print(n,"The number is in the given range")
    else:
        print(n,"The number is not in the given range")
check=int(input("Enter the number:"))
check_range(check)

Enter the number:2000
2000 The number is in the given range


8.Write a program to calculate the sum of all elements in the list.

test_score = [10, 32, 23, 14, 25]

In [61]:
test_score = [10, 32, 23, 14, 25]
total=sum(test_score)


print("Sum of all elements in given list:",total)

Sum of all elements in given list: 104


9.Replace all even numbers in the array with -1.

Use the array given below num_array = np.array([0, 21, 32, 13, 44, 45, 26, 28, 38, 34, 65, 48, 76])

In [64]:
import numpy as np
num_array = np.array([0, 21, 32, 13, 44, 45, 26, 28, 38, 34, 65, 48, 76])
print(num_array)
print(np.where(num_array%2==0,-1,num_array))

[ 0 21 32 13 44 45 26 28 38 34 65 48 76]
[-1 21 -1 13 -1 45 -1 -1 -1 -1 65 -1 -1]


10.Find the minimum value along each of the rows. 

Create a 2D Numpy array from list of lists 

Score = np.array([[210, 402, 383], [140, 375, 106], [140, 125, 217], [292, 240, 295]])

In [38]:
import numpy as np
Score = np.array([[210, 402, 383], [140, 375, 106], [140, 125, 217], [292, 240, 295]])


In [40]:
Score

array([[210, 402, 383],
       [140, 375, 106],
       [140, 125, 217],
       [292, 240, 295]])

min_value=np.amin(arr2D,axis=1)

In [67]:
print("The minimum value in each row",Score.min(axis=1))

The minimum value in each row [210 106 125 240]
